package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * AccountPermissions generated by hbm2java
 */
public class AccountPermissions implements java.io.Serializable {

	private int permissionId;
	private String permissionName;

	public AccountPermissions() {
	}

	public AccountPermissions(int permissionId, String permissionName) {
		this.permissionId = permissionId;
		this.permissionName = permissionName;
	}

	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

}
