package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * AdditionalGradeEntries generated by hbm2java
 */
public class AdditionalGradeEntries implements java.io.Serializable {

	private static final long serialVersionUID = -3955170939205033552L;

	private Integer entryId;
	private CourseUsers courseUser;
	private Integer pointsEarned;
	private int totalPoints;
	private String title;
	private String comments;
	private CourseUsers createdBy;

	public AdditionalGradeEntries() {
	}
	
	public AdditionalGradeEntries(CourseUsers courseUser, int totalPoints, 
			String title, CourseUsers createdBy) {
		this.createdBy = createdBy;
		this.courseUser = courseUser;
		this.totalPoints = totalPoints;
		this.title = title;
	}

	public AdditionalGradeEntries(CourseUsers courseUser, Integer pointsEarned, 
			int totalPoints, String title, String comments, CourseUsers createdBy) {
		this.createdBy = createdBy;
		this.courseUser = courseUser;
		this.pointsEarned = pointsEarned;
		this.totalPoints = totalPoints;
		this.title = title;
		this.comments = comments;
	}
	
	public Integer getEntryId() {
		return this.entryId;
	}

	public void setEntryId(Integer entryId) {
		this.entryId = entryId;
	}

	public CourseUsers getCourseUser() {
		return this.courseUser;
	}

	public void setCourseUser(CourseUsers courseUser) {
		this.courseUser = courseUser;
	}
	
	public Integer getPointsEarned() {
		return this.pointsEarned;
	}

	public void setPointsEarned(Integer pointsEarned) {
		this.pointsEarned = pointsEarned;
	}

	public int getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public CourseUsers getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(CourseUsers createdBy) {
		this.createdBy = createdBy;
	}
}
