package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Announcements generated by hbm2java
 */
public class Announcements implements java.io.Serializable {

	private static final long serialVersionUID = 5414999601181931682L;

	private Integer announcementId;
	private Courses course;
	private String title;
	private String description;
	private Date datePosted;
	private CourseUsers creator;
	
	public Announcements() {
	}

	public Announcements(Courses course, String title, String description, 
			Date datePosted, CourseUsers creator) {
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.datePosted = datePosted;
	}
	
	public Integer getAnnouncementId() {
		return this.announcementId;
	}

	public void setAnnouncementId(Integer announcementId) {
		this.announcementId = announcementId;
	}

	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}
	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatePosted() {
		return this.datePosted;
	}

	public void setDatePosted(Date datePosted) {
		this.datePosted = datePosted;
	}
	
	public CourseUsers getCreator() {
		return this.creator;
	}

	public void setCreator(CourseUsers creator) {
		this.creator = creator;
	}
}