package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Announcements generated by hbm2java
 */
public class Announcements implements java.io.Serializable {

	private Integer announcementId;
	private int courseId;
	private String title;
	private String description;
	private Date datePosted;
	private int creatorUid;

	public Announcements() {
	}

	public Announcements(int courseId, String title, String description,
			Date datePosted, int creatorUid) {
		this.courseId = courseId;
		this.title = title;
		this.description = description;
		this.datePosted = datePosted;
		this.creatorUid = creatorUid;
	}

	public Integer getAnnouncementId() {
		return this.announcementId;
	}

	public void setAnnouncementId(Integer announcementId) {
		this.announcementId = announcementId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatePosted() {
		return this.datePosted;
	}

	public void setDatePosted(Date datePosted) {
		this.datePosted = datePosted;
	}

	public int getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(int creatorUid) {
		this.creatorUid = creatorUid;
	}

}
