package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Announcements generated by hbm2java
 */
public class Announcements implements java.io.Serializable {

	private static final long serialVersionUID = 5414999601181931682L;

	private Integer announcementId;
//Begin Modification (Ben Andow)
//	private int courseId;
	private Courses course;
//End Modificaiton (Ben Andow)
	private String title;
	private String description;
	private Date datePosted;
//Begin Modification (Ben Andow)
//	private int creatorUid;
	private CourseUsers creator;
//End Modification (Ben Andow)
	
	public Announcements() {
	}

//Begin Modification (Ben Andow)
	public Announcements(Courses course, String title, String description, 
			Date datePosted, CourseUsers creator) {
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.datePosted = datePosted;
	}
//	public Announcements(int courseId, String title, String description,
//			Date datePosted, int creatorUid) {
//		this.courseId = courseId;
//		this.title = title;
//		this.description = description;
//		this.datePosted = datePosted;
//		this.creatorUid = creatorUid;
//	}
//End Modification (Ben Andow)
	
	public Integer getAnnouncementId() {
		return this.announcementId;
	}

	public void setAnnouncementId(Integer announcementId) {
		this.announcementId = announcementId;
	}

//Begin Modification (Ben Andow)
	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}
	
//	public int getCourseId() {
//		return this.courseId;
//	}
//
//	public void setCourseId(int courseId) {
//		this.courseId = courseId;
//	}
//End Modification (Ben Andow)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatePosted() {
		return this.datePosted;
	}

	public void setDatePosted(Date datePosted) {
		this.datePosted = datePosted;
	}
	
//Begin Modification (Ben Andow)
	public CourseUsers getCreator() {
		return this.creator;
	}

	public void setCreator(CourseUsers creator) {
		this.creator = creator;
	}

//	public int getCreatorUid() {
//		return this.creatorUid;
//	}
//
//	public void setCreatorUid(int creatorUid) {
//		this.creatorUid = creatorUid;
//	}
//End Modification (Ben Andow)
	
}
