package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assignments generated by hbm2java
 */
public class Assignments implements java.io.Serializable {

	private static final long serialVersionUID = -6312664479960794538L;

	private Integer assignmentId;
	private Courses course;
	private String title;
	private String description;
	private int totalPoints;
	private Date startDate;
	private Date endDate;
	private Date lateSubmissionDate;
	private Integer timer;
	private int numAttempts;
	private AssignmentTypes assignmentType;
	private String assignmentFilename;
	private CourseUsers creator;
	private Date visibleDate;
	private Set<AssignmentSubmission> assignmentSubmissions = new HashSet<AssignmentSubmission>(0);
	
	public Assignments() {
	}

	public Assignments(Courses course, String title, String description,
			int totalPoints, Date startDate, Date endDate, int numAttempts,
			AssignmentTypes assignmentType, String assignmentFilename, 
			CourseUsers creator, Date visibleDate) {
		this.assignmentType = assignmentType;
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.numAttempts = numAttempts;
		this.assignmentFilename = assignmentFilename;
		this.visibleDate = visibleDate;
	}

	public Assignments(Courses course, String title, String description,
			int totalPoints, Date startDate, Date endDate,
			Date lateSubmissionDate, Integer timer, int numAttempts,
			AssignmentTypes assignmentType, String assignmentFilename, CourseUsers creator,
			Date visibleDate, Set<AssignmentSubmission> assignmentSubmissions) {
		this.assignmentType = assignmentType;
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.lateSubmissionDate = lateSubmissionDate;
		this.timer = timer;
		this.numAttempts = numAttempts;
		this.assignmentFilename = assignmentFilename;
		this.visibleDate = visibleDate;
		this.assignmentSubmissions = assignmentSubmissions;
	}

	public Integer getAssignmentId() {
		return this.assignmentId;
	}

	public void setAssignmentId(Integer assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}
	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLateSubmissionDate() {
		return this.lateSubmissionDate;
	}

	public void setLateSubmissionDate(Date lateSubmissionDate) {
		this.lateSubmissionDate = lateSubmissionDate;
	}

	public Integer getTimer() {
		return this.timer;
	}

	public void setTimer(Integer timer) {
		this.timer = timer;
	}

	public int getNumAttempts() {
		return this.numAttempts;
	}

	public void setNumAttempts(int numAttempts) {
		this.numAttempts = numAttempts;
	}

	public AssignmentTypes getAssignmentType() {
		return this.assignmentType;
	}

	public void setAssignmentType(AssignmentTypes assignmentType) {
		this.assignmentType = assignmentType;
	}

	public String getAssignmentFilename() {
		return this.assignmentFilename;
	}

	public void setAssignmentFilename(String assignmentFilename) {
		this.assignmentFilename = assignmentFilename;
	}
	
	public CourseUsers getCreator() {
		return this.creator;
	}

	public void setCreator(CourseUsers creator) {
		this.creator = creator;
	}

	public Date getVisibleDate() {
		return this.visibleDate;
	}

	public void setVisibleDate(Date visibleDate) {
		this.visibleDate = visibleDate;
	}

	public Set<AssignmentSubmission> getAssignmentSubmissions() {
		return this.assignmentSubmissions;
	}

	public void setAssignmentSubmissions(
			Set<AssignmentSubmission> assignmentSubmissions) {
		this.assignmentSubmissions = assignmentSubmissions;
	}
}
