package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Assignments generated by hbm2java
 */
public class Assignments implements java.io.Serializable {

	private Integer assignmentId;
	private int courseId;
	private String title;
	private String description;
	private int totalPoints;
	private Date startDate;
	private Date endDate;
	private Date lateSubmissionDate;
	private Integer timer;
	private int numAttempts;
	private int assignmentTypeId;
	private String assignmentFilename;
	private int creatorUid;
	private Date visibleDate;

	public Assignments() {
	}

	public Assignments(int courseId, String title, String description,
			int totalPoints, Date startDate, Date endDate, int numAttempts,
			int assignmentTypeId, String assignmentFilename, int creatorUid,
			Date visibleDate) {
		this.courseId = courseId;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.numAttempts = numAttempts;
		this.assignmentTypeId = assignmentTypeId;
		this.assignmentFilename = assignmentFilename;
		this.creatorUid = creatorUid;
		this.visibleDate = visibleDate;
	}

	public Assignments(int courseId, String title, String description,
			int totalPoints, Date startDate, Date endDate,
			Date lateSubmissionDate, Integer timer, int numAttempts,
			int assignmentTypeId, String assignmentFilename, int creatorUid,
			Date visibleDate) {
		this.courseId = courseId;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.lateSubmissionDate = lateSubmissionDate;
		this.timer = timer;
		this.numAttempts = numAttempts;
		this.assignmentTypeId = assignmentTypeId;
		this.assignmentFilename = assignmentFilename;
		this.creatorUid = creatorUid;
		this.visibleDate = visibleDate;
	}

	public Integer getAssignmentId() {
		return this.assignmentId;
	}

	public void setAssignmentId(Integer assignmentId) {
		this.assignmentId = assignmentId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLateSubmissionDate() {
		return this.lateSubmissionDate;
	}

	public void setLateSubmissionDate(Date lateSubmissionDate) {
		this.lateSubmissionDate = lateSubmissionDate;
	}

	public Integer getTimer() {
		return this.timer;
	}

	public void setTimer(Integer timer) {
		this.timer = timer;
	}

	public int getNumAttempts() {
		return this.numAttempts;
	}

	public void setNumAttempts(int numAttempts) {
		this.numAttempts = numAttempts;
	}

	public int getAssignmentTypeId() {
		return this.assignmentTypeId;
	}

	public void setAssignmentTypeId(int assignmentTypeId) {
		this.assignmentTypeId = assignmentTypeId;
	}

	public String getAssignmentFilename() {
		return this.assignmentFilename;
	}

	public void setAssignmentFilename(String assignmentFilename) {
		this.assignmentFilename = assignmentFilename;
	}

	public int getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(int creatorUid) {
		this.creatorUid = creatorUid;
	}

	public Date getVisibleDate() {
		return this.visibleDate;
	}

	public void setVisibleDate(Date visibleDate) {
		this.visibleDate = visibleDate;
	}

}
