package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Assignments generated by hbm2java
 */
public class Assignments implements java.io.Serializable {

	private static final long serialVersionUID = -6312664479960794538L;

	private Integer assignmentId;
//Begin Modification (Ben Andow)
//	private int courseId;
	private Courses course;
//End Modification (Ben Andow)	
	private String title;
	private String description;
	private int totalPoints;
	private Date startDate;
	private Date endDate;
	private Date lateSubmissionDate;
	private Integer timer;
	private int numAttempts;
//Begin Modification (Ben Andow)
//	private int assignmentTypeId;
	private AssignmentTypes assignmentType;
//End Modification (Ben Andow)	
	private String assignmentFilename;
//Begin Modification (Ben Andow)
//	private int creatorUid;
	private CourseUsers creator;
//End Modification (Ben Andow)	
	private Date visibleDate;
//Begin Modification (Ben Andow)
	private Set<AssignmentSubmission> assignmentSubmissions = new HashSet<AssignmentSubmission>(0);
//End Modification (Ben Andow)
	
	
	public Assignments() {
	}

//Begin Modification (Ben Andow)
	public Assignments(Courses course, String title, String description,
			int totalPoints, Date startDate, Date endDate, int numAttempts,
			AssignmentTypes assignmentType, String assignmentFilename, 
			CourseUsers creator, Date visibleDate) {
		this.assignmentType = assignmentType;
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.numAttempts = numAttempts;
		this.assignmentFilename = assignmentFilename;
		this.visibleDate = visibleDate;
	}

	public Assignments(Courses course, String title, String description,
			int totalPoints, Date startDate, Date endDate,
			Date lateSubmissionDate, Integer timer, int numAttempts,
			AssignmentTypes assignmentType, String assignmentFilename, CourseUsers creator,
			Date visibleDate, Set<AssignmentSubmission> assignmentSubmissions) {
		this.assignmentType = assignmentType;
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.totalPoints = totalPoints;
		this.startDate = startDate;
		this.endDate = endDate;
		this.lateSubmissionDate = lateSubmissionDate;
		this.timer = timer;
		this.numAttempts = numAttempts;
		this.assignmentFilename = assignmentFilename;
		this.visibleDate = visibleDate;
		this.assignmentSubmissions = assignmentSubmissions;
	}
	
//	public Assignments(int courseId, String title, String description,
//			int totalPoints, Date startDate, Date endDate, int numAttempts,
//			int assignmentTypeId, String assignmentFilename, int creatorUid,
//			Date visibleDate) {
//		this.courseId = courseId;
//		this.title = title;
//		this.description = description;
//		this.totalPoints = totalPoints;
//		this.startDate = startDate;
//		this.endDate = endDate;
//		this.numAttempts = numAttempts;
//		this.assignmentTypeId = assignmentTypeId;
//		this.assignmentFilename = assignmentFilename;
//		this.creatorUid = creatorUid;
//		this.visibleDate = visibleDate;
//	}
//
//	public Assignments(int courseId, String title, String description,
//			int totalPoints, Date startDate, Date endDate,
//			Date lateSubmissionDate, Integer timer, int numAttempts,
//			int assignmentTypeId, String assignmentFilename, int creatorUid,
//			Date visibleDate) {
//		this.courseId = courseId;
//		this.title = title;
//		this.description = description;
//		this.totalPoints = totalPoints;
//		this.startDate = startDate;
//		this.endDate = endDate;
//		this.lateSubmissionDate = lateSubmissionDate;
//		this.timer = timer;
//		this.numAttempts = numAttempts;
//		this.assignmentTypeId = assignmentTypeId;
//		this.assignmentFilename = assignmentFilename;
//		this.creatorUid = creatorUid;
//		this.visibleDate = visibleDate;
//	}
//End Modification (Ben Andow)
	
	public Integer getAssignmentId() {
		return this.assignmentId;
	}

	public void setAssignmentId(Integer assignmentId) {
		this.assignmentId = assignmentId;
	}

//Begin Modification (Ben Andow)
	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}
	
//	public int getCourseId() {
//		return this.courseId;
//	}

//	public void setCourseId(int courseId) {
//		this.courseId = courseId;
//	}
//End Modification (Ben Andow)
	
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLateSubmissionDate() {
		return this.lateSubmissionDate;
	}

	public void setLateSubmissionDate(Date lateSubmissionDate) {
		this.lateSubmissionDate = lateSubmissionDate;
	}

	public Integer getTimer() {
		return this.timer;
	}

	public void setTimer(Integer timer) {
		this.timer = timer;
	}

	public int getNumAttempts() {
		return this.numAttempts;
	}

	public void setNumAttempts(int numAttempts) {
		this.numAttempts = numAttempts;
	}

//Begin Modification (Ben Andow)
	public AssignmentTypes getAssignmentType() {
		return this.assignmentType;
	}

	public void setAssignmentType(AssignmentTypes assignmentType) {
		this.assignmentType = assignmentType;
	}
	
//	public int getAssignmentTypeId() {
//		return this.assignmentTypeId;
//	}
//
//	public void setAssignmentTypeId(int assignmentTypeId) {
//		this.assignmentTypeId = assignmentTypeId;
//	}
//End Modification(Ben Andow)

	public String getAssignmentFilename() {
		return this.assignmentFilename;
	}

	public void setAssignmentFilename(String assignmentFilename) {
		this.assignmentFilename = assignmentFilename;
	}
	
//Begin Modification (Ben Andow)
	
	public CourseUsers getCreator() {
		return this.creator;
	}

	public void setCreator(CourseUsers creator) {
		this.creator = creator;
	}
	
//	public int getCreatorUid() {
//		return this.creatorUid;
//	}
//
//	public void setCreatorUid(int creatorUid) {
//		this.creatorUid = creatorUid;
//	}
//End Modification (Ben Andow)
	
	public Date getVisibleDate() {
		return this.visibleDate;
	}

	public void setVisibleDate(Date visibleDate) {
		this.visibleDate = visibleDate;
	}

//Begin Modification (Ben Andow)
	public Set<AssignmentSubmission> getAssignmentSubmissions() {
		return this.assignmentSubmissions;
	}

	public void setAssignmentSubmissions(
			Set<AssignmentSubmission> assignmentSubmissions) {
		this.assignmentSubmissions = assignmentSubmissions;
	}
//End Modification (Ben Andow)
}
