package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AssignmentSubmission generated by hbm2java
 */
public class AssignmentSubmission implements java.io.Serializable {

	private static final long serialVersionUID = 5547185119652612040L;

	private Integer submissionId;
//Begin Modification (Ben Andow)
//	private int assignmentId;
//	private int courseUid;
	private Assignments assignment;
	private CourseUsers user;
// End Modification (Ben Andow)
	private Date dateStarted;
	private Date dateSubmitted;
	private Integer pointsEarned;
	private String submissionFilename;
	private String comments;

	public AssignmentSubmission() {
	}

//Begin Modification (Ben Andow)
	public AssignmentSubmission(Assignments assignment,
			CourseUsers user, Date dateStarted) {
		this.assignment = assignment;
		this.user = user;
		this.dateStarted = dateStarted;
	}

	public AssignmentSubmission(Assignments assignment,
			CourseUsers user, Date dateStarted, Date dateSubmitted,
			Integer pointsEarned, String submissionFilename, String comments) {
		this.assignment = assignment;
		this.user = user;
		this.dateStarted = dateStarted;
		this.dateSubmitted = dateSubmitted;
		this.pointsEarned = pointsEarned;
		this.submissionFilename = submissionFilename;
		this.comments = comments;
	}
	
//	public AssignmentSubmission(int assignmentId, int courseUid,
//			Date dateStarted) {
//		this.assignmentId = assignmentId;
//		this.courseUid = courseUid;
//		this.dateStarted = dateStarted;
//	}
//
//	public AssignmentSubmission(int assignmentId, int courseUid,
//			Date dateStarted, Date dateSubmitted, Integer pointsEarned,
//			String submissionFilename, String comments) {
//		this.assignmentId = assignmentId;
//		this.courseUid = courseUid;
//		this.dateStarted = dateStarted;
//		this.dateSubmitted = dateSubmitted;
//		this.pointsEarned = pointsEarned;
//		this.submissionFilename = submissionFilename;
//		this.comments = comments;
//	}
//End Modification (Ben Andow)
	
	public Integer getSubmissionId() {
		return this.submissionId;
	}

	public void setSubmissionId(Integer submissionId) {
		this.submissionId = submissionId;
	}

//Begin Modification (Ben Andow)
	public Assignments getAssignment() {
		return this.assignment;
	}

	public void setAssignment(Assignments assignment) {
		this.assignment = assignment;
	}

	public CourseUsers getUser() {
		return this.user;
	}

	public void setUser(CourseUsers user) {
		this.user = user;
	}
	
//	public int getAssignmentId() {
//		return this.assignmentId;
//	}
//
//	public void setAssignmentId(int assignmentId) {
//		this.assignmentId = assignmentId;
//	}
//
//	public int getCourseUid() {
//		return this.courseUid;
//	}
//
//	public void setCourseUid(int courseUid) {
//		this.courseUid = courseUid;
//	}
//End Modification (Ben Andow)

	public Date getDateStarted() {
		return this.dateStarted;
	}

	public void setDateStarted(Date dateStarted) {
		this.dateStarted = dateStarted;
	}

	public Date getDateSubmitted() {
		return this.dateSubmitted;
	}

	public void setDateSubmitted(Date dateSubmitted) {
		this.dateSubmitted = dateSubmitted;
	}

	public Integer getPointsEarned() {
		return this.pointsEarned;
	}

	public void setPointsEarned(Integer pointsEarned) {
		this.pointsEarned = pointsEarned;
	}

	public String getSubmissionFilename() {
		return this.submissionFilename;
	}

	public void setSubmissionFilename(String submissionFilename) {
		this.submissionFilename = submissionFilename;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
