package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CourseMaterial generated by hbm2java
 */
public class CourseMaterial implements java.io.Serializable {

	private Integer courseMaterialId;
	private String title;
	private String description;
	private Date uploadDate;
	private int creatorUid;
	private String materialFilename;
	private int courseId;

	public CourseMaterial() {
	}

	public CourseMaterial(String title, Date uploadDate, int creatorUid,
			String materialFilename, int courseId) {
		this.title = title;
		this.uploadDate = uploadDate;
		this.creatorUid = creatorUid;
		this.materialFilename = materialFilename;
		this.courseId = courseId;
	}

	public CourseMaterial(String title, String description, Date uploadDate,
			int creatorUid, String materialFilename, int courseId) {
		this.title = title;
		this.description = description;
		this.uploadDate = uploadDate;
		this.creatorUid = creatorUid;
		this.materialFilename = materialFilename;
		this.courseId = courseId;
	}

	public Integer getCourseMaterialId() {
		return this.courseMaterialId;
	}

	public void setCourseMaterialId(Integer courseMaterialId) {
		this.courseMaterialId = courseMaterialId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public int getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(int creatorUid) {
		this.creatorUid = creatorUid;
	}

	public String getMaterialFilename() {
		return this.materialFilename;
	}

	public void setMaterialFilename(String materialFilename) {
		this.materialFilename = materialFilename;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

}
