package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CourseMaterial generated by hbm2java
 */
public class CourseMaterial implements java.io.Serializable {

	private static final long serialVersionUID = 7559627526224071501L;

	private Integer courseMaterialId;
	private String title;
	private String description;
	private Date uploadDate;
	private CourseUsers creator;
	private String materialFilename;
	private Courses course;

	public CourseMaterial() {
	}

	public CourseMaterial(String title, Date uploadDate, CourseUsers creator,
			String materialFilename, Courses course) {
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.uploadDate = uploadDate;
		this.materialFilename = materialFilename;
	}

	public CourseMaterial(String title, String description, Date uploadDate,
			CourseUsers creator, String materialFilename, Courses course) {
		this.course = course;
		this.creator = creator;
		this.title = title;
		this.description = description;
		this.uploadDate = uploadDate;
		this.materialFilename = materialFilename;
	}
	
	public Integer getCourseMaterialId() {
		return this.courseMaterialId;
	}

	public void setCourseMaterialId(Integer courseMaterialId) {
		this.courseMaterialId = courseMaterialId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public CourseUsers getCreator() {
		return this.creator;
	}

	public void setCreator(CourseUsers creator) {
		this.creator = creator;
	}
	
	public String getMaterialFilename() {
		return this.materialFilename;
	}

	public void setMaterialFilename(String materialFilename) {
		this.materialFilename = materialFilename;
	}

	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}
}