package com.myboard.dao;

import java.util.HashSet;
import java.util.Set;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * CourseSection generated by hbm2java
 */
public class CourseSection implements java.io.Serializable {

	private static final long serialVersionUID = -9051594078880063185L;

	private Integer courseSectionId;
//Begin Modification (Ben Andow)
	private CourseInfo courseInfo;
//	private int courseInfoId;
//End Modification (Ben Andow)
	private int section;
//Begin Modification (Ben Andow)
	private Set<Courses> courses = new HashSet<Courses>(0);
//End Modification (Ben Andow)
	
	public CourseSection() {
	}

//Begin Modification (Ben Andow)
	public CourseSection(CourseInfo courseInfo, int section) {
		this.courseInfo = courseInfo;
		this.section = section;
	}

	public CourseSection(CourseInfo courseInfo, int section,
			Set<Courses> courses) {
		this.courseInfo = courseInfo;
		this.section = section;
		this.courses = courses;
	}
	
//	public CourseSection(int courseInfoId, int section) {
//		this.courseInfoId = courseInfoId;
//		this.section = section;
//	}
//End Modification (Ben Andow)

	public Integer getCourseSectionId() {
		return this.courseSectionId;
	}

	public void setCourseSectionId(Integer courseSectionId) {
		this.courseSectionId = courseSectionId;
	}

//Begin Modification (Ben Andow)
	
	public CourseInfo getCourseInfo() {
		return this.courseInfo;
	}

	public void setCourseInfo(CourseInfo courseInfo) {
		this.courseInfo = courseInfo;
	}
	
//	public int getCourseInfoId() {
//		return this.courseInfoId;
//	}
//
//	public void setCourseInfoId(int courseInfoId) {
//		this.courseInfoId = courseInfoId;
//	}
//End Modification (Ben Andow)
	
	public int getSection() {
		return this.section;
	}

	public void setSection(int section) {
		this.section = section;
	}

//Begin Modification (Ben Andow)
	public Set<Courses> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Courses> courses) {
		this.courses = courses;
	}
//End Modification (Ben Andow)
}
