package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

	private Integer courseId;
	private int courseSectionId;
	private int courseSemesterId;
	private String courseRootDirectory;

	public Courses() {
	}

	public Courses(int courseSectionId, int courseSemesterId,
			String courseRootDirectory) {
		this.courseSectionId = courseSectionId;
		this.courseSemesterId = courseSemesterId;
		this.courseRootDirectory = courseRootDirectory;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public int getCourseSectionId() {
		return this.courseSectionId;
	}

	public void setCourseSectionId(int courseSectionId) {
		this.courseSectionId = courseSectionId;
	}

	public int getCourseSemesterId() {
		return this.courseSemesterId;
	}

	public void setCourseSemesterId(int courseSemesterId) {
		this.courseSemesterId = courseSemesterId;
	}

	public String getCourseRootDirectory() {
		return this.courseRootDirectory;
	}

	public void setCourseRootDirectory(String courseRootDirectory) {
		this.courseRootDirectory = courseRootDirectory;
	}

}
