package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * CourseSection generated by hbm2java
 */
public class CourseSection implements java.io.Serializable {

	private Integer courseSectionId;
	private int courseInfoId;
	private int section;

	public CourseSection() {
	}

	public CourseSection(int courseInfoId, int section) {
		this.courseInfoId = courseInfoId;
		this.section = section;
	}

	public Integer getCourseSectionId() {
		return this.courseSectionId;
	}

	public void setCourseSectionId(Integer courseSectionId) {
		this.courseSectionId = courseSectionId;
	}

	public int getCourseInfoId() {
		return this.courseInfoId;
	}

	public void setCourseInfoId(int courseInfoId) {
		this.courseInfoId = courseInfoId;
	}

	public int getSection() {
		return this.section;
	}

	public void setSection(int section) {
		this.section = section;
	}

}
