package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * MessageRecipient generated by hbm2java
 */
public class MessageRecipient implements java.io.Serializable {

	private static final long serialVersionUID = 2298710433170661934L;

	private Integer messageRecipientId;
	private Message message;
	private CourseUsers recipient;
	private boolean deleted;
	private boolean isNew;

	public MessageRecipient() {
	}

	public MessageRecipient(Message message, CourseUsers recipient,
			boolean deleted, boolean isNew) {
		this.message = message;
		this.recipient = recipient;
		this.deleted = deleted;
		this.isNew = isNew;
	}
	
	public Integer getMessageRecipientId() {
		return this.messageRecipientId;
	}

	public void setMessageRecipientId(Integer messageRecipientId) {
		this.messageRecipientId = messageRecipientId;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public CourseUsers getRecipient() {
		return this.recipient;
	}

	public void setRecipient(CourseUsers recipient) {
		this.recipient = recipient;
	}
	
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public boolean isIsNew() {
		return this.isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}
}