package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer messageId;
	private Integer parentId;
	private int fromUid;
	private int courseId;
	private String title;
	private String message;
	private String attachmentFilename;

	public Message() {
	}

	public Message(int fromUid, int courseId, String title, String message) {
		this.fromUid = fromUid;
		this.courseId = courseId;
		this.title = title;
		this.message = message;
	}

	public Message(Integer parentId, int fromUid, int courseId, String title,
			String message, String attachmentFilename) {
		this.parentId = parentId;
		this.fromUid = fromUid;
		this.courseId = courseId;
		this.title = title;
		this.message = message;
		this.attachmentFilename = attachmentFilename;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public int getFromUid() {
		return this.fromUid;
	}

	public void setFromUid(int fromUid) {
		this.fromUid = fromUid;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getAttachmentFilename() {
		return this.attachmentFilename;
	}

	public void setAttachmentFilename(String attachmentFilename) {
		this.attachmentFilename = attachmentFilename;
	}

}
