package com.myboard.dao;

import java.util.HashSet;
import java.util.Set;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private static final long serialVersionUID = 8596488949762199031L;

	private Integer messageId;
	private Integer parentId;
//Begin Modification (Ben Andow)
	private Courses course;
	private CourseUsers sender;
//	private int fromUid;
//	private int courseId;
//End Modification (Ben Andow)
	private String title;
	private String message;
	private String attachmentFilename;
//Begin Modification (Ben Andow)
	private Set<MessageRecipient> recipients = new HashSet<MessageRecipient>(
			0);
//End Modification (Ben Andow)
	
	public Message() {
	}

//Begin Modification (Ben Andow)
	
	public Message(CourseUsers sender, Courses course, String title, String message) {
		this.course = course;
		this.sender = sender;
		this.title = title;
		this.message = message;
	}

	public Message(Integer parentId, CourseUsers sender, Courses course, 
			String title, String message, String attachmentFilename,
			Set<MessageRecipient> recipients) {
		this.course = course;
		this.sender = sender;
		this.parentId = parentId;
		this.title = title;
		this.message = message;
		this.attachmentFilename = attachmentFilename;
		this.recipients = recipients;
	}
	
//	public Message(int fromUid, int courseId, String title, String message) {
//		this.fromUid = fromUid;
//		this.courseId = courseId;
//		this.title = title;
//		this.message = message;
//	}
//
//	public Message(Integer parentId, int fromUid, int courseId, String title,
//			String message, String attachmentFilename) {
//		this.parentId = parentId;
//		this.fromUid = fromUid;
//		this.courseId = courseId;
//		this.title = title;
//		this.message = message;
//		this.attachmentFilename = attachmentFilename;
//	}
//End Modification (Ben Andow)
	
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

//Begin Modification (Ben Andow)
	public Courses getCourse() {
		return this.course;
	}

	public void setCourse(Courses course) {
		this.course = course;
	}

	public CourseUsers getSender() {
		return this.sender;
	}

	public void setSender(CourseUsers sender) {
		this.sender = sender;
	}
	
//	public int getFromUid() {
//		return this.fromUid;
//	}
//
//	public void setFromUid(int fromUid) {
//		this.fromUid = fromUid;
//	}
//
//	public int getCourseId() {
//		return this.courseId;
//	}
//
//	public void setCourseId(int courseId) {
//		this.courseId = courseId;
//	}
//End Modification (Ben Andow)

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getAttachmentFilename() {
		return this.attachmentFilename;
	}

	public void setAttachmentFilename(String attachmentFilename) {
		this.attachmentFilename = attachmentFilename;
	}
	
//Begin Modification (Ben Andow)
	public Set<MessageRecipient> getRecipients() {
		return this.recipients;
	}

	public void setRecipients(Set<MessageRecipient> recipients) {
		this.recipients = recipients;
	}
//End Modification (Ben Andow)
}
