package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * MessageRecipient generated by hbm2java
 */
public class MessageRecipient implements java.io.Serializable {

	private static final long serialVersionUID = 2298710433170661934L;

	private Integer messageRecipientId;
//Begin Modification (Ben Andow)
	private Message message;
	private CourseUsers recipient;
//	private int messageId;
//	private int courseUid;
//End Modification (Ben Andow)
	private boolean deleted;
	private boolean isNew;

	public MessageRecipient() {
	}

//Begin Modification (Ben Andow)
	public MessageRecipient(Message message, CourseUsers recipient,
			boolean deleted, boolean isNew) {
		this.message = message;
		this.recipient = recipient;
		this.deleted = deleted;
		this.isNew = isNew;
	}
	
//	public MessageRecipient(int messageId, int courseUid, boolean deleted,
//			boolean isNew) {
//		this.messageId = messageId;
//		this.courseUid = courseUid;
//		this.deleted = deleted;
//		this.isNew = isNew;
//	}
//End Modification (Ben Andow)
	
	public Integer getMessageRecipientId() {
		return this.messageRecipientId;
	}

	public void setMessageRecipientId(Integer messageRecipientId) {
		this.messageRecipientId = messageRecipientId;
	}

//Begin Modification (Ben Andow)
	
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public CourseUsers getRecipient() {
		return this.recipient;
	}

	public void setRecipient(CourseUsers recipient) {
		this.recipient = recipient;
	}
	
//	public int getMessageId() {
//		return this.messageId;
//	}
//
//	public void setMessageId(int messageId) {
//		this.messageId = messageId;
//	}
//
//	public int getCourseUid() {
//		return this.courseUid;
//	}
//
//	public void setCourseUid(int courseUid) {
//		this.courseUid = courseUid;
//	}
//End Modification (Ben Andow)
	
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public boolean isIsNew() {
		return this.isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}

}
