package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

/**
 * MessageRecipient generated by hbm2java
 */
public class MessageRecipient implements java.io.Serializable {

	private Integer messageRecipientId;
	private int messageId;
	private int courseUid;
	private boolean deleted;
	private boolean isNew;

	public MessageRecipient() {
	}

	public MessageRecipient(int messageId, int courseUid, boolean deleted,
			boolean isNew) {
		this.messageId = messageId;
		this.courseUid = courseUid;
		this.deleted = deleted;
		this.isNew = isNew;
	}

	public Integer getMessageRecipientId() {
		return this.messageRecipientId;
	}

	public void setMessageRecipientId(Integer messageRecipientId) {
		this.messageRecipientId = messageRecipientId;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public int getCourseUid() {
		return this.courseUid;
	}

	public void setCourseUid(int courseUid) {
		this.courseUid = courseUid;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public boolean isIsNew() {
		return this.isNew;
	}

	public void setIsNew(boolean isNew) {
		this.isNew = isNew;
	}

}
