package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Semester generated by hbm2java
 */
public class Semester implements java.io.Serializable {

	private Integer courseSemesterId;
	private String semesterName;
	private Date startDate;
	private Date endDate;

	public Semester() {
	}

	public Semester(String semesterName, Date startDate, Date endDate) {
		this.semesterName = semesterName;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Integer getCourseSemesterId() {
		return this.courseSemesterId;
	}

	public void setCourseSemesterId(Integer courseSemesterId) {
		this.courseSemesterId = courseSemesterId;
	}

	public String getSemesterName() {
		return this.semesterName;
	}

	public void setSemesterName(String semesterName) {
		this.semesterName = semesterName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
