package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semester generated by hbm2java
 */
public class Semester implements java.io.Serializable {

	private static final long serialVersionUID = 5587137855312689088L;

	private Integer courseSemesterId;
	private String semesterName;
	private Date startDate;
	private Date endDate;
	private Set<Courses> courses = new HashSet<Courses>(0);

	public Semester() {
	}

	public Semester(String semesterName, Date startDate, Date endDate) {
		this.semesterName = semesterName;
		this.startDate = startDate;
		this.endDate = endDate;
	}
	
	public Semester(String semesterName, Date startDate, Date endDate,
			Set<Courses> courses) {
		this.semesterName = semesterName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.courses = courses;
	}
	
	public Integer getCourseSemesterId() {
		return this.courseSemesterId;
	}

	public void setCourseSemesterId(Integer courseSemesterId) {
		this.courseSemesterId = courseSemesterId;
	}

	public String getSemesterName() {
		return this.semesterName;
	}

	public void setSemesterName(String semesterName) {
		this.semesterName = semesterName;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	public Set<Courses> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Courses> courses) {
		this.courses = courses;
	}
}