package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 3025125083485005603L;

	private String uid;
	private String firstName;
	private String lastName;
//Begin Modification (Ben Andow)
	private Department department;
//	private int department;
//End Modification (Ben Andow)
	private String password;
//Begin Modification (Ben Andow)
	private AccountPermissions permission;
//	private int permissionId;
//End Modification (Ben Andow)
	private Date creationDate;
	private Date lastLogin;
	private String privateDirectory;
	private boolean active;
	private String emailAddress;
//Begin Modification (Ben Andow)
	private Set<CourseUsers> courseUsers = new HashSet<CourseUsers>(0);
	private Set<AdditionalCalendarEntries> additionalCalendarEntries = new HashSet<AdditionalCalendarEntries>(
			0);
//End Modification (Ben Andow)
	
	public Users() {
	}

//Begin Modification (Ben Andow)
	public Users(String uid, String firstName, String lastName, Department department,
			String password, AccountPermissions permission, Date creationDate,
			Date lastLogin, String privateDirectory, boolean active, String emailAddress) {
		this.uid = uid;
		this.department = department;
		this.permission = permission;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.creationDate = creationDate;
		this.lastLogin = lastLogin;
		this.privateDirectory = privateDirectory;
		this.active = active;
		this.emailAddress = emailAddress;
	}

	public Users(String uid, String firstName, String lastName, Department department,
			String password, AccountPermissions permission, Date creationDate,
			Date lastLogin, String privateDirectory, boolean active,
			String emailAddress, Set<CourseUsers> courseUsers,
			Set<AdditionalCalendarEntries> additionalCalendarEntries) {
		this.uid = uid;
		this.department = department;
		this.permission = permission;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.creationDate = creationDate;
		this.lastLogin = lastLogin;
		this.privateDirectory = privateDirectory;
		this.active = active;
		this.emailAddress = emailAddress;
		this.courseUsers = courseUsers;
		this.additionalCalendarEntries = additionalCalendarEntries;
	}
	
//	public Users(String uid, String firstName, String lastName, int department,
//			String password, int permissionId, Date creationDate,
//			Date lastLogin, String privateDirectory, boolean active) {
//		this.uid = uid;
//		this.firstName = firstName;
//		this.lastName = lastName;
//		this.department = department;
//		this.password = password;
//		this.permissionId = permissionId;
//		this.creationDate = creationDate;
//		this.lastLogin = lastLogin;
//		this.privateDirectory = privateDirectory;
//		this.active = active;
//	}
//
//	public Users(String uid, String firstName, String lastName, int department,
//			String password, int permissionId, Date creationDate,
//			Date lastLogin, String privateDirectory, boolean active,
//			String emailAddress) {
//		this.uid = uid;
//		this.firstName = firstName;
//		this.lastName = lastName;
//		this.department = department;
//		this.password = password;
//		this.permissionId = permissionId;
//		this.creationDate = creationDate;
//		this.lastLogin = lastLogin;
//		this.privateDirectory = privateDirectory;
//		this.active = active;
//		this.emailAddress = emailAddress;
//	}
//End Modification (Ben Andow)
	
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

//Begin Modification (Ben Andow)
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	
//	public int getDepartment() {
//		return this.department;
//	}
//
//	public void setDepartment(int department) {
//		this.department = department;
//	}
//End Modification (Ben Andow)

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
//Begin Modification (Ben Andow)
	public AccountPermissions getPermission() {
		return this.permission;
	}

	public void setPermission(AccountPermissions permission) {
		this.permission = permission;
	}
	
//	public int getPermissionId() {
//		return this.permissionId;
//	}
//
//	public void setPermissionId(int permissionId) {
//		this.permissionId = permissionId;
//	}
//End Modification (Ben Andow)
	
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public String getPrivateDirectory() {
		return this.privateDirectory;
	}

	public void setPrivateDirectory(String privateDirectory) {
		this.privateDirectory = privateDirectory;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	
//Begin Modification (Ben Andow)	
	public Set<CourseUsers> getCourseUsers() {
		return this.courseUsers;
	}

	public void setCourseUsers(Set<CourseUsers> courseUsers) {
		this.courseUsers = courseUsers;
	}

	public Set<AdditionalCalendarEntries> getAdditionalCalendarEntries() {
		return this.additionalCalendarEntries;
	}

	public void setAdditionalCalendarEntries(
			Set<AdditionalCalendarEntries> additionalCalendarEntries) {
		this.additionalCalendarEntries = additionalCalendarEntries;
	}
//End Modification (Ben Andow)
}