package com.myboard.dao;

// Generated Mar 13, 2013 12:50:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String uid;
	private String firstName;
	private String lastName;
	private int department;
	private String password;
	private int permissionId;
	private Date creationDate;
	private Date lastLogin;
	private String privateDirectory;
	private boolean active;
	private String emailAddress;

	public Users() {
	}

	public Users(String uid, String firstName, String lastName, int department,
			String password, int permissionId, Date creationDate,
			Date lastLogin, String privateDirectory, boolean active) {
		this.uid = uid;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
		this.password = password;
		this.permissionId = permissionId;
		this.creationDate = creationDate;
		this.lastLogin = lastLogin;
		this.privateDirectory = privateDirectory;
		this.active = active;
	}

	public Users(String uid, String firstName, String lastName, int department,
			String password, int permissionId, Date creationDate,
			Date lastLogin, String privateDirectory, boolean active,
			String emailAddress) {
		this.uid = uid;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
		this.password = password;
		this.permissionId = permissionId;
		this.creationDate = creationDate;
		this.lastLogin = lastLogin;
		this.privateDirectory = privateDirectory;
		this.active = active;
		this.emailAddress = emailAddress;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public int getDepartment() {
		return this.department;
	}

	public void setDepartment(int department) {
		this.department = department;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public String getPrivateDirectory() {
		return this.privateDirectory;
	}

	public void setPrivateDirectory(String privateDirectory) {
		this.privateDirectory = privateDirectory;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
